name: Publish Allure Report
on:
  push:
    branches:
      - master
jobs:
  publish-report:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 

      - name: Run Tests
        run: mvn clean test

        
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{  secrets.GITHUB_TOKEN  }}
          publish_dir: ./allure-report
