name: Playwright Tests
on:
  push:
      branches:
        - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache

      - name: Run Tests
        run: mvn clean test

      - name: Install Allure
        run: |
          curl -o allure.tgz -Ls https://github.com/allure-framework/allure2/releases/latest/download/allure-2.34.1.tgz
          tar -zxvf allure.tgz

      - name: Generate Allure Report
        run: |
          ./allure-2.34.1/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()

        with:
          name: allure-report
          path: allure-report
    
      
